services:
  server:
    build: server
    container_name: server
    depends_on:
      - jaeger
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4318/v1/traces"
  client:
    build: client
    container_name: client
    depends_on: 
      - jaeger
    ports:
      - 8080:8080
    environment:
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4318/v1/traces"
  jaeger:
        image: jaegertracing/all-in-one:1.44
        container_name: jaeger
        environment:
            COLLECTOR_OTLP_ENABLED: true
        ports:
          - "4318:4318"
          - "4317:4317"
          - "5775:5775"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "8090:16686"
          - "14268:14268"
          - "14250:14250"
          - "9411:9411"

